## run with 'carton install'
requires 'App::Yath', '>= 1.0';
requires 'Archive::Zip';
requires 'Class::Inspector';
requires 'Crypt::Blowfish';
requires 'Crypt::CBC';
requires 'Crypt::DES';
requires 'Digest::MD5::File';
requires 'Email::MIME';
requires 'Email::Sender';
requires 'Email::Sender::Simple';
requires 'Email::Sender::Transport::SMTP::TLS';
requires 'Email::Valid';
requires 'File::Copy::Recursive';
requires 'File::Grep';
requires 'File::Touch';
requires 'File::Which';
requires 'Log::Log4perl';
requires 'Math::Round';
requires 'Mojo::JWT';
requires 'Mojolicious', '>= 8.30';
requires 'Mojolicious::Plugin::BrowserDetect';
requires 'Mojolicious::Plugin::Mojolyst';
requires 'Mojolicious::Plugin::OAuth2';
requires 'Mojolicious::Plugin::RenderFile';
requires 'Mojolicious::Plugin::Web::Auth';
requires 'Perl6::Slurp';
requires 'Scalar::Util::Numeric';
requires 'Term::ReadKey';
requires 'Test2::MojoX';
requires 'Test2::V0';
requires 'Try::Tiny';
requires 'YAML';
requires 'YAML::Tiny';
requires 'common::sense';
